services:
  sonarqube:
    image: sonarqube:latest
    environment:
      - SONAR_HOST_URL=http://172.17.0.1:9000
    env_file:
      - .env
    ports:
      - 9000:9000
    restart: always
    networks:
      - sonar_network  

  sonar-scanner-cli:
    image: sonarsource/sonar-scanner-cli:latest
    environment:
      - SONAR_HOST_URL=http://172.17.0.1:9000
      # - SONAR_LOGIN=${SONAR_LOGIN}
    networks:
      - sonar_network
    volumes:
      - ./scanner_cache:/opt/sonar-scanner/.sonar/cache
      # - ./projects:/usr/src
    env_file:
      - .env
    restart: always
    depends_on:
      - sonarqube

networks:
  sonar_network:
    driver: bridge