services:
  sonarqube:
    image: sonarqube:25.3.0.104237-community
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - ./sonar-flutter-plugin:/opt/sonarqube/extensions/plugins
    restart: always
    networks:
      - sonar_network

  sonar-scanner-cli:
    image: sonarsource/sonar-scanner-cli:11.2
    networks:
      - sonar_network
    volumes:
      - ./tmp/scanner_cache:/opt/sonar-scanner/.sonar/cache
    env_file:
      - .env
    restart: always
    depends_on:
      - sonarqube

networks:
  sonar_network:
    driver: bridge
